# from https://github.com/marketplace/actions/run-arduino-builder

name: Build examples
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build all example sketches
      uses: arduino/setup-arduino-cli@v1.0.0
      with:
        board: "arduino:avr:uno"
